# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - name: Upload build results
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          path: dist/
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build results
        uses: actions/download-artifact@v2
        with:
          name: build-results
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i is-ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm dist-tag add ngx-pug-builders@${{steps.package-version.outputs.current-version}} stable
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Download build results
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build-results
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm i is-ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
